name: background_downloader_hls
description: "A Flutter package to download and combine HLS (.m3u8) as an extension to background_downloader."
version: 0.1.0
homepage: https://github.com/abhishek-m-raj/background_downloader_hls
repository: https://github.com/abhishek-m-raj/background_downloader_hls.git
topics:
  - hls
  - download
  - media
  - background_downloader

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  background_downloader: ^9.2.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_hls_parser: ^2.0.1
  http: ^1.4.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
